In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df = pd.read_csv("D:/machine learning/py-master/py-master/ML/3_gradient_descent/Exercise/test_scores.csv")
df.head()

     name  math  cs
0   david    92  98
1   laura    56  68
2  sanjay    88  81
3     wei    70  80
4    jeff    80  83

In [3]:
df

     name  math  cs
0   david    92  98
1   laura    56  68
2  sanjay    88  81
3     wei    70  80
4    jeff    80  83
5   aamir    49  52
6  venkat    65  66
7   virat    35  30
8  arthur    66  68
9    paul    67  73

In [63]:
%matplotlib inline
import math
def gradient_descent(x,y):
    m_curr = b_curr = 0
    rate = 0.01
    n = len(x)
    prev_cost = 1000000
    stopping_threshold = 1e-6 
    #plt.scatter(x,y,color='red',marker='+',linewidth='5')
    for i in range(10000):
        y_predicted = m_curr * x + b_curr
        #cost = np.sum([val**2 for val in (y-y_predicted)])*(1/n)
        cost = np.sum((y-y_predicted)**2)*(1/n)
        print ("m = {} , b= {}, cost ={} at iteration {}".format(m_curr,b_curr,cost,i))
        
        if(math.isclose(prev_cost,cost,rel_tol=1e-20)):
            break;
        #if (abs(prev_cost-cost)<=stopping_threshold):
        #    break
        prev_cost = cost 
        #previous_cost = current_cost
        
    # plt.plot(x,y_predicted,color='green')
        md = -(2/n)*sum(x*(y-y_predicted))
        yd = -(2/n)*sum(y-y_predicted)
        m_curr = m_curr - rate * md
        b_curr = b_curr - rate * yd

In [53]:
x = np.array([1,2,3,4,5])
y = np.array([5,7,9,11,13])

In [64]:
#gradient_descent(x,y)
gradient_descent(df.math,df.cs)

m = 0 , b= 0, cost =5199.1 at iteration 0
m = 98.918 , b= 1.3980000000000001, cost =45366108.340850405 at iteration 1
m = -9169.587968000002 , b= -129.386408, cost =398290329619.79016 at iteration 2
m = 859278.7790833284 , b= 12125.168845408005, cost =3496779946139641.0 at iteration 3
m = -80513336.3321037 , b= -1136112.3853868274, cost =3.0699891720627802e+19 at iteration 4
m = 7544007292.656351 , b= 106452428.60001147, cost =2.6952892837845242e+23 at iteration 5
m = -706864823521.7386 , b= -9974470361.562872, cost =2.366322457874498e+27 at iteration 6
m = 66232422560018.44 , b= 934596423272.1094, cost =2.077506859218773e+31 at iteration 7
m = -6205901966243919.0 , b= -87570612045376.58, cost =1.8239419296970386e+35 at iteration 8
m = 5.814858905354231e+17 , b= 8205265827097408.0, cost =1.6013252366146005e+39 at iteration 9
m = -5.448456046050343e+19 , b= -7.688239892447695e+17, cost =1.4058794699920812e+43 at iteration 10
m = 5.105140772789593e+21 , b= 7.203792526577272e+19, cost =1.234288350019247e+47 at iteration 11
m = -4.783458302630841e+23 , b= -6.74987090568644e+21, cost =1.0836403571650534e+51 at iteration 12
m = 4.482045520657572e+25 , b= 6.324551557439078e+23, cost =9.513793301690755e+54 at iteration 13
m = -4.1996252038400877e+27 , b= -5.926032210335615e+25, cost =8.352610936721472e+58 at iteration 14
m = 3.9350006088606955e+29 , b= 5.552624156669068e+27, cost =7.3331537955360665e+62 at iteration 15
m = -3.6870504009680314e+31 , b= -5.202745096702534e+29, cost =6.43812395864958e+66 at iteration 16
m = 3.4547239023717715e+33 , b= 4.874912433745606e+31, cost =5.652334761091385e+70 at iteration 17
m = -3.237036640043024e+35 , b= -4.567736991717981e+33, cost =4.962453108489603e+74 at iteration 18
m = 3.0330661740543987e+37 , b= 4.279917128578644e+35, cost =4.35677324412456e+78 at iteration 19
m = -2.8419481887825394e+39 , b= -4.0102332206766067e+37, cost =3.8250181282815046e+82 at iteration 20
m = 2.662872830409765e+41 , b= 3.757542494650841e+39, cost =3.3581650597521543e+86 at iteration 21
m = -2.4950812752051536e+43 , b= -3.520774184979868e+41, cost =2.9482925806698926e+90 at iteration 22
m = 2.3378625140433015e+45 , b= 3.298924996661283e+43, cost =2.5884460669942977e+94 at iteration 23
m = -2.190550339535319e+47 , b= -3.09105485379457e+45, cost =2.2725197240146025e+98 at iteration 24
m = 2.052520523005154e+49 , b= 2.8962829160519996e+47, cost =1.9951529845983015e+102 at iteration 25
m = -1.923188169348813e+51 , b= -2.7137838461575763e+49, cost =1.751639552293685e+106 at iteration 26
m = 1.8020052385678148e+53 , b= 2.5427843125576694e+51, cost =1.5378475459501542e+110 at iteration 27
m = -1.6884582234744865e+55 , b= -2.382559712463536e+53, cost =1.35014939088815e+114 at iteration 28
m = 1.5820659737284843e+57 , b= 2.2324311013797718e+55, cost =1.1853602670278786e+118 at iteration 29
m = -1.4823776569839887e+59 , b= -2.0917623161077335e+57, cost =1.0406840695784933e+122 at iteration 30
m = 1.3889708485080324e+61 , b= 1.9599572790327534e+59, cost =9.136659653608772e+125 at iteration 31
m = -1.3014497411748039e+63 , b= -1.8364574722722103e+61, cost =8.021507397503799e+129 at iteration 32
m = 1.219443468250852e+65 , b= 1.7207395709812706e+63, cost =7.042462274797934e+133 at iteration 33
m = -1.1426045318640812e+67 , b= -1.6123132257875217e+65, cost =6.182912068046699e+137 at iteration 34
m = 1.0706073304972364e+69 , b= 1.510718984957695e+67, cost =5.428272122663853e+141 at iteration 35
m = -1.0031467792662015e+71 , b= -1.4155263474917225e+69, cost =4.765737877782639e+145 at iteration 36
m = 9.399370171366024e+72 , b= 1.3263319388942262e+71, cost =4.184067601346858e+149 at iteration 37
m = -8.807101956006055e+74 , b= -1.2427578018933375e+73, cost =3.6733916429297385e+153 at iteration 38
m = 8.252153436809802e+76 , b= 1.164449794863854e+75, cost =3.225044967725274e+157 at iteration 39
m = -7.732173044529361e+78 , b= -1.0910760911681242e+77, cost =2.831420130186499e+161 at iteration 40
m = 7.244957385772907e+80 , b= 1.0223257730556751e+79, cost =2.4858381926004374e+165 at iteration 41
m = -6.788441906224863e+82 , b= -9.579075141633148e+80, cost =2.1824353983751556e+169 at iteration 42
m = 6.360692142190374e+84 , b= 8.975483450328412e+82, cost =1.9160636771367338e+173 at iteration 43
m = -5.959895523392907e+86 , b= -8.409924964153124e+84, cost =1.68220329342901e+177 at iteration 44
m = 5.584353692289688e+88 , b= 7.880003154604224e+86, cost =1.4768861568589032e+181 at iteration 45
m = -5.232475307358434e+90 , b= -7.3834725019839e+88, cost =1.2966284924310827e+185 at iteration 46
m = 4.9027692998596465e+92 , b= 6.918228980111427e+90, cost =1.1383717286373908e+189 at iteration 47
m = -4.5938385555002596e+94 , b= -6.482301140607395e+92, cost =9.994306003033937e+192 at iteration 48
m = 4.304373994225029e+96 , b= 6.073841758970393e+94, cost =8.774475856128477e+196 at iteration 49
m = -4.033149023049007e+98 , b= -5.69112000704673e+96, cost =7.703529042077514e+200 at iteration 50
m = 3.779014338425252e+100 , b= 5.332514118724415e+98, cost =6.763293976207482e+204 at iteration 51
m = -3.540893056123038e+102 , b= -4.996504517772638e+100, cost =5.937816961389488e+208 at iteration 52
m = 3.317776147979637e+104 , b= 4.681667378706207e+102, cost =5.213091489294608e+212 at iteration 53
m = -3.108718166189119e+106 , b= -4.386668593389475e+104, cost =4.5768205811107413e+216 at iteration 54
m = 2.912833237010043e+108 , b= 4.110258117813446e+106, cost =4.0182081351718755e+220 at iteration 55
m = -2.7292913069155488e+110 , b= -3.8512646750908465e+108, cost =3.5277757411331614e+224 at iteration 56
m = 2.557314625279079e+112 , b= 3.608590792223282e+110, cost =3.097201852435973e+228 at iteration 57
m = -2.3961744486912823e+114 , b= -3.381208149609062e+112, cost =2.7191805881775087e+232 at iteration 58
m = 2.2451879529427813e+116 , b= 3.1681532235853846e+114, cost =2.387297768566809e+236 at iteration 59
m = -2.103715339587469e+118 , b= -2.968523203540419e+116, cost =2.095922080564669e+240 at iteration 60
m = 1.9711571248255345e+120 , b= 2.7814721662941635e+118, cost =1.840109527030539e+244 at iteration 61
m = -1.8469515992179773e+122 , b= -2.606207491537232e+120, cost =1.6155195380909946e+248 at iteration 62
m = 1.7305724474682703e+124 , b= 2.441986503138153e+122, cost =1.418341321326373e+252 at iteration 63
m = -1.621526518185095e+126 , b= -2.288113322086855e+124, cost =1.245229201102075e+256 at iteration 64
m = 1.5193517341756278e+128 , b= 2.143935917738836e+126, cost =1.0932458498968772e+260 at iteration 65
m = -1.4236151344143378e+130 , b= -2.0088433448647983e+128, cost =9.598124483901925e+263 at iteration 66
m = 1.3339110393902257e+132 , b= 1.8822631547978803e+130, cost =8.426649286358364e+267 at iteration 67
m = -1.2498593320582444e+134 , b= -1.7636589697083224e+132, cost =7.398155578663304e+271 at iteration 68
m = 1.1711038471105164e+136 , b= 1.6525282097266731e+134, cost =6.49519211090368e+275 at iteration 69
m = -1.0973108617419513e+138 , b= -1.5483999632843285e+136, cost =5.702437602044571e+279 at iteration 70
m = 1.028167681514955e+140 , b= 1.4508329916470608e+138, cost =5.006440771878509e+283 at iteration 71
m = -9.633813153308937e+141 , b= -1.359413859185839e+140, cost =4.395392102728275e+287 at iteration 72
m = 9.026772338935685e+143 , b= 1.2737551814620527e+142, cost =3.8589234582070315e+291 at iteration 73
m = -8.457982064037382e+145 , b= -1.1934939837034794e+144, cost =3.387932159012003e+295 at iteration 74
m = 7.925032105552447e+147 , b= 1.1182901627151002e+146, cost =2.9744265307093664e+299 at iteration 75
m = -7.425664112138921e+149 , b= -1.0478250457071987e+148, cost =2.6113903027998675e+303 at iteration 76
m = 6.957762034512808e+151 , b= 9.818000399338293e+149, cost =inf at iteration 77
m = -6.519343158784951e+153 , b= -9.199353674195595e+151, cost =inf at iteration 78

In [29]:
x =80
y = -6.519343158784951e+153*x+-9.199353674195595e+151
y

-5.21639446239538e+155